use_frameworks!

platform :ios, '12.0'
source 'https://github.com/CocoaPods/Specs.git'
target 'YFAdsSDK_Example' do
  
  # 亿帆SDK【必须】
  pod 'YFAdsSDK', :path => '../'
  #  百度【必须】
  pod 'BaiduMobAdSDK','5.373'
  # 优量汇【必须】
  pod 'GDTMobSDK' ,'4.15.22'
  # 京东【必须】
  pod 'JADYun', '2.6.8'
  pod 'JADYunMotion', '2.6.8'  #京东摇一摇组件
  #  穿山甲【必须】
  pod 'Ads-CN','6.6.1.3', :subspecs => ['BUAdSDK', 'CSJMediation','BUAdLive-Lib']
  #  快手【必须】
  pod 'KSAdSDK','3.3.72'
  # 微信OpenSDK【必须】，如App内已通过其他方式集成OpenSDK，无需再次集成
  pod 'WechatOpenSDK-XCFramework'
 
 # Demo依赖库
  pod 'AFNetworking'
  pod 'Bugly'
  pod 'SDWebImage','5.18.0'
  pod 'Masonry'
  pod "STDebugConsole"
  pod 'JPFPSStatus'
  pod 'YYKit'
  pod 'FLAnimatedImage'
  pod 'MJRefresh'
  
  target 'YFAdsSDK_Tests' do
    inherit! :search_paths
  end

  post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
  end
  
end
