use_frameworks!

platform :ios, '13.0'
source 'https://github.com/CocoaPods/Specs.git'
target 'YFAdsSDK_Example' do
  
  # 亿帆SDK【必须】
#pod 'YFAdsSDK', :path => '../'
  pod 'YFAdsSDK', '6.0.7.0'
  #  百度【必须】
  #pod 'BaiduMobAdSDK','10.02'
  # 优量汇【必须】
  pod 'GDTMobSDK' ,'4.15.60'
  # 京东【必须】
  pod 'JADYun', '2.6.8'
  pod 'JADYunMotion', '2.6.8'  #京东摇一摇组件
  #  穿山甲【必须】注意：穿山甲70xx版本运行环境配置发生变更，支持系统iOS 13.0及以上版本，请Xcode修改项目支持最低13.0，如需支持13.0以下请联系技术同学获取支持的穿山甲版本
  pod 'Ads-CN', '7.1.0.9', :subspecs => ['BUAdSDK','CSJMediation','BUAdLive-Framework']
  # Gromore-Adn适配器
  pod 'GMBaiduAdapter', '5.394.0'
  pod 'GMGdtAdapter', '4.15.41.2'
  pod 'GMKsAdapter', '4.6.30.1.2'
  # 快手【必须】
  pod 'KSAdSDK','4.9.20.1'
  pod 'WechatOpenSDK'
 
 # Demo依赖库
  pod 'AFNetworking'
  pod 'Bugly'
  pod 'SDWebImage','5.18.0'
  pod 'Masonry'
  pod "STDebugConsole"
  pod 'JPFPSStatus'
  pod 'YYKit'
  #pod 'FLAnimatedImage'
  pod 'MJRefresh'
  
  target 'YFAdsSDK_Tests' do
    inherit! :search_paths
  end

  post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
  end
  
end
