use_frameworks!

platform :ios, '12.0'
source 'https://github.com/CocoaPods/Specs.git'
target 'YFAdsSDK_Example' do
 # 可选直接引入cocoapods版本
 # pod 'YFAdsSDK', '6.0.3.6'
 #  直接导入本地SDK
   pod 'YFAdsSDK', :path => '../'
 #  pod 'YFAdsSDK/CSJ', :path => '../'
 #  pod 'YFAdsSDK/GRO', :path => '../'
 #  pod 'YFAdsSDK/GDT', :path => '../'
 #  pod 'YFAdsSDK/KS', :path => '../'
 #  pod 'YFAdsSDK/BD', :path => '../'
 #  pod 'YFAdsSDK/YF', :path => '../'
 #  pod 'YFAdsSDK/JD', :path => '../'
 #  pod 'YFAdsSDK/TX', :path => '../'
  pod 'JADYun', '2.6.8' # 京东
  pod 'JADYunMotion', '2.6.8'  #京东摇一摇组件
  pod 'BaiduMobAdSDK','5.371' #百度
 # 穿山甲 使用gromore聚合功能 CSJMediation必须引入
  pod 'Ads-CN','6.5.0.9', :subspecs => ['BUAdSDK', 'CSJMediation','BUAdLive-Lib']
 #  优量汇
  pod 'GDTMobSDK' ,'4.15.10'
 #  快手
  pod 'KSAdSDK','3.3.72'
 #  Tanx
  pod 'TanxSDK', '3.6.2'
 #  微信小程序广告支持
  pod 'WechatOpenSDK'
 
 
 # Demo依赖库
  pod 'AFNetworking'
  pod 'Bugly'
  pod 'SDWebImage','5.18.0'
  pod 'Masonry'
  pod "STDebugConsole"
  pod 'JPFPSStatus'
  pod 'YYKit'
  pod 'FLAnimatedImage'
  pod 'MJRefresh'
  
  target 'YFAdsSDK_Tests' do
    inherit! :search_paths
  end

  post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
  end
  
end
