//
//  YFAdsSDK.h>
//  YFAdsSDK
//
//  Created by 麻明康 on 2024/11/26.
//

#import <Foundation/Foundation.h>

//! Project version number for YFAdsSDK.
FOUNDATION_EXPORT double YFAdsSDKVersionNumber;

//! Project version string for YFAdsSDK.
FOUNDATION_EXPORT const unsigned char YFAdsSDKVersionString[];

// In this header, you should import all the public headers of your framework using statements like #import <YFAdsSDK/PublicHeader.h>
#import <YFAdsSDK/ADXNativeAd.h>
#import <YFAdsSDK/ADXNativeAdsManager.h>
#import <YFAdsSDK/ADXNativeMediaView.h>
#import <YFAdsSDK/CGGeometry+YFAdditions.h>
#import <YFAdsSDK/NSArray+Addition.h>
#import <YFAdsSDK/NSData+YFAdd.h>
#import <YFAdsSDK/NSData+YF_ImageContentType.h>
#import <YFAdsSDK/NSNumber+YFAdd.h>
#import <YFAdsSDK/NSObject+YFAdModel.h>
#import <YFAdsSDK/NSString+YFAdd.h>
#import <YFAdsSDK/NSString+YFUrlEncode.h>
#import <YFAdsSDK/UIApplication+YFAds.h>
#import <YFAdsSDK/UIButton+YFEdge.h>
#import <YFAdsSDK/UIButton+YF_WebCache.h>
#import <YFAdsSDK/UIColor+YFExpanded.h>
#import <YFAdsSDK/UIImage+YFImageEffects.h>
#import <YFAdsSDK/UIImage+YF_GIF.h>
#import <YFAdsSDK/UIImage+YF_MultiFormat.h>
#import <YFAdsSDK/UIImage+YF_WebP.h>
#import <YFAdsSDK/UIImageView+YFCache.h>
#import <YFAdsSDK/UIImageView+YF_HighlightedWebCache.h>
#import <YFAdsSDK/UIImageView+YF_WebCache.h>
#import <YFAdsSDK/UILabel+YFEdge.h>
#import <YFAdsSDK/UIScrollView+YFPlayer.h>
#import <YFAdsSDK/UITapGestureRecognizer+YFBlock.h>
#import <YFAdsSDK/UIView+ViewVisiable.h>
#import <YFAdsSDK/UIView+YFAutoLayout.h>
#import <YFAdsSDK/UIView+YFFrame.h>
#import <YFAdsSDK/UIView+YF_WebCacheOperation.h>
#import <YFAdsSDK/YFASLLogCapture.h>
#import <YFAdsSDK/YFASLLogger.h>
#import <YFAdsSDK/YFAVPlayerManager.h>
#import <YFAdsSDK/YFAbstractDatabaseLogger.h>
#import <YFAdsSDK/YFAd.h>
#import <YFAdsSDK/YFAdAESEncrypt.h>
#import <YFAdsSDK/YFAdAPConst.h>
#import <YFAdsSDK/YFAdBanner.h>
#import <YFAdsSDK/YFAdBannerDelegate.h>
#import <YFAdsSDK/YFAdBannerView600x100.h>
#import <YFAdsSDK/YFAdBannerView600x150.h>
#import <YFAdsSDK/YFAdBannerView600x260.h>
#import <YFAdsSDK/YFAdBannerViewN600x260.h>
#import <YFAdsSDK/YFAdBannerViewN600x260R.h>
#import <YFAdsSDK/YFAdBannerViewR600x150.h>
#import <YFAdsSDK/YFAdBannerViewR640x100.h>
#import <YFAdsSDK/YFAdBannerViewTDBP.h>
#import <YFAdsSDK/YFAdBaseAdPosition.h>
#import <YFAdsSDK/YFAdBaseAdapter.h>
#import <YFAdsSDK/YFAdBaseCustomView.h>
#import <YFAdsSDK/YFAdBaseDelegate.h>
#import <YFAdsSDK/YFAdBaseView.h>
#import <YFAdsSDK/YFAdClassInfo.h>
#import <YFAdsSDK/YFAdCommonDelegate.h>
#import <YFAdsSDK/YFAdConst.h>
#import <YFAdsSDK/YFAdCrashManager.h>
#import <YFAdsSDK/YFAdCustomModel.h>
#import <YFAdsSDK/YFAdDBManager.h>
#import <YFAdsSDK/YFAdDataManager.h>
#import <YFAdsSDK/YFAdDetailViewController.h>
#import <YFAdsSDK/YFAdDraw.h>
#import <YFAdsSDK/YFAdDrawDelegate.h>
#import <YFAdsSDK/YFAdDrawView.h>
#import <YFAdsSDK/YFAdEmptyAdapter.h>
#import <YFAdsSDK/YFAdEnvelopeVideoView.h>
#import <YFAdsSDK/YFAdError.h>
#import <YFAdsSDK/YFAdFeedbackView.h>
#import <YFAdsSDK/YFAdFullScreenVideo.h>
#import <YFAdsSDK/YFAdFullScreenVideoDelegate.h>
#import <YFAdsSDK/YFAdFusionBanner.h>
#import <YFAdsSDK/YFAdFusionBannerDelegate.h>
#import <YFAdsSDK/YFAdFusionBannerView.h>
#import <YFAdsSDK/YFAdImage.h>
#import <YFAdsSDK/YFAdInteractionType.h>
#import <YFAdsSDK/YFAdInterstitial.h>
#import <YFAdsSDK/YFAdInterstitialDelegate.h>
#import <YFAdsSDK/YFAdInterstitialVideoView.h>
#import <YFAdsSDK/YFAdInterstitialViewProtocol.h>
#import <YFAdsSDK/YFAdLogManager.h>
#import <YFAdsSDK/YFAdMarkImageView.h>
#import <YFAdsSDK/YFAdMarkView.h>
#import <YFAdsSDK/YFAdMedia.h>
#import <YFAdsSDK/YFAdMediaDelegate.h>
#import <YFAdsSDK/YFAdMediaMetal.h>
#import <YFAdsSDK/YFAdMediaRender.h>
#import <YFAdsSDK/YFAdModel.h>
#import <YFAdsSDK/YFAdNative.h>
#import <YFAdsSDK/YFAdNativeAdExtraDataModel.h>
#import <YFAdsSDK/YFAdNativeConfiguration.h>
#import <YFAdsSDK/YFAdNativeExpress.h>
#import <YFAdsSDK/YFAdNativeExpressDelegate.h>
#import <YFAdsSDK/YFAdNativeExpressView.h>
#import <YFAdsSDK/YFAdNativeOffer.h>
#import <YFAdsSDK/YFAdNativePrepareInfo.h>
#import <YFAdsSDK/YFAdNativeRendering.h>
#import <YFAdsSDK/YFAdNativeView.h>
#import <YFAdsSDK/YFAdParameterModel.h>
#import <YFAdsSDK/YFAdPatch.h>
#import <YFAdsSDK/YFAdPatchDelegate.h>
#import <YFAdsSDK/YFAdReportModel.h>
#import <YFAdsSDK/YFAdResponseModel.h>
#import <YFAdsSDK/YFAdRewardModel.h>
#import <YFAdsSDK/YFAdRewardVideo.h>
#import <YFAdsSDK/YFAdSDKLocation.h>
#import <YFAdsSDK/YFAdRewardVideoDelegate.h>
#import <YFAdsSDK/YFAdSDKManager.h>
#import <YFAdsSDK/YFAdSDKSetting.h>
#import <YFAdsSDK/YFAdSDKSwitch.h>
#import <YFAdsSDK/YFAdSplash.h>
#import <YFAdsSDK/YFAdSplashAdExtraDataModel.h>
#import <YFAdsSDK/YFAdSplashDelegate.h>
#import <YFAdsSDK/YFAdSupplierDelegate.h>
#import <YFAdsSDK/YFAdSupplierManager.h>
#import <YFAdsSDK/YFAdUtils.h>
#import <YFAdsSDK/YFAdView.h>
#import <YFAdsSDK/YFAdXBannerView.h>
#import <YFAdsSDK/YFAdXBannerView600x410.h>
#import <YFAdsSDK/YFAdXBannerViewB600x400.h>
#import <YFAdsSDK/YFAdsAnimationView.h>
#import <YFAdsSDK/YFAdsButton.h>
#import <YFAdsSDK/YFAdsCloseButton.h>
#import <YFAdsSDK/YFAdsCountButton.h>
#import <YFAdsSDK/YFAdsDetailButton.h>
#import <YFAdsSDK/YFAdxCustomExpressAdapter.h>
#import <YFAdsSDK/YFAdxDataManager.h>
#import <YFAdsSDK/YFAnimatedControl.h>
#import <YFAdsSDK/YFAnimatedSwitch.h>
#import <YFAdsSDK/YFAnimationCache.h>
#import <YFAdsSDK/YFAnimationTransitionController.h>
#import <YFAdsSDK/YFAnimationView.h>
#import <YFAdsSDK/YFAnimationView_Compat.h>
#import <YFAdsSDK/YFAnimationView_Internal.h>
#import <YFAdsSDK/YFAnimatorNode.h>
#import <YFAdsSDK/YFAppENVInfo.h>
#import <YFAdsSDK/YFArrayInterpolator.h>
#import <YFAdsSDK/YFAssertMacros.h>
#import <YFAdsSDK/YFAsset.h>
#import <YFAdsSDK/YFAssetGroup.h>
#import <YFAdsSDK/YFBannerAdapter.h>
#import <YFAdsSDK/YFBannerView.h>

#import <YFAdsSDK/YFBezierData.h>
#import <YFAdsSDK/YFBezierPath.h>
#import <YFAdsSDK/YFBlockCallback.h>
#import <YFAdsSDK/YFBlurImageView.h>
#import <YFAdsSDK/YFCacheProvider.h>
#import <YFAdsSDK/YFCircleAnimator.h>
#import <YFAdsSDK/YFColorInterpolator.h>
#import <YFAdsSDK/YFCocoaLumberjack.h>
#import <YFAdsSDK/YFComposition.h>
#import <YFAdsSDK/YFCompositionContainer.h>
#import <YFAdsSDK/YFContextFilterLogFormatter+Deprecated.h>
#import <YFAdsSDK/YFContextFilterLogFormatter.h>

#import <YFAdsSDK/YFDB.h>
#import <YFAdsSDK/YFDatabase.h>
#import <YFAdsSDK/YFDatabaseAdditions.h>
#import <YFAdsSDK/YFDatabasePool.h>
#import <YFAdsSDK/YFDatabaseQueue.h>
#import <YFAdsSDK/YFDispatchQueueLogFormatter.h>
#import <YFAdsSDK/YFDomainManager.h>
#import <YFAdsSDK/YFDomainManagerApi.h>
#import <YFAdsSDK/YFDomainManagerApiTest.h>
#import <YFAdsSDK/YFDomainManagerHeader.h>
#import <YFAdsSDK/YFDomainManagerTracker.h>
#import <YFAdsSDK/YFDomainManagerTrackerTest.h>
#import <YFAdsSDK/YFDownloadNetworkTool.h>
#import <YFAdsSDK/YFFileLogger+Buffering.h>
#import <YFAdsSDK/YFFileLogger+Internal.h>
#import <YFAdsSDK/YFFileLogger.h>
#import <YFAdsSDK/YFFillRenderer.h>
#import <YFAdsSDK/YFFloatView.h>
#import <YFAdsSDK/YFFullScreenVideoAd.h>
#import <YFAdsSDK/YFFusionBannerAdapter.h>
#import <YFAdsSDK/YFFullScreenVideoAdapter.h>

#import <YFAdsSDK/YFGlobalMotionActionHandler.h>
#import <YFAdsSDK/YFGlobalMotionManager.h>
#import <YFAdsSDK/YFGlobalMotionModel.h>
#import <YFAdsSDK/YFGradientFillRender.h>
#import <YFAdsSDK/YFGradientView.h>

#import <YFAdsSDK/YFHelpers.h>
#import <YFAdsSDK/YFInterpolatorCallback.h>
#import <YFAdsSDK/YFInterstitialAd.h>
#import <YFAdsSDK/YFInterstitialAdapter.h>
#import <YFAdsSDK/YFInterstitialView.h>
#import <YFAdsSDK/YFInvoker.h>

#import <YFAdsSDK/YFKVOController.h>
#import <YFAdsSDK/YFKeyChain.h>
#import <YFAdsSDK/YFKeypath.h>
#import <YFAdsSDK/YFKeyframe.h>
#import <YFAdsSDK/YFKit.h>
#import <YFAdsSDK/YFKitImpressionTimer.h>

#import <YFAdsSDK/YFLandScapeControlView.h>
#import <YFAdsSDK/YFLandscapeRotationManager.h>
#import <YFAdsSDK/YFLandscapeRotationManager_iOS15.h>
#import <YFAdsSDK/YFLandscapeRotationManager_iOS16.h>
#import <YFAdsSDK/YFLandscapeViewController.h>
#import <YFAdsSDK/YFLandscapeViewController_iOS15.h>
#import <YFAdsSDK/YFLandscapeWindow.h>
#import <YFAdsSDK/YFLayerContainer.h>
#import <YFAdsSDK/YFLayer.h>
#import <YFAdsSDK/YFLayerGroup.h>
#import <YFAdsSDK/YFLegacyMacros.h>
#import <YFAdsSDK/YFLoadingView.h>
#import <YFAdsSDK/YFLog+LOGV.h>
#import <YFAdsSDK/YFLog.h>
#import <YFAdsSDK/YFLogMacros.h>
#import <YFAdsSDK/YFLoggerNames.h>
#import <YFAdsSDK/YFMD5.h>
#import <YFAdsSDK/YFManager.h>
#import <YFAdsSDK/YFMaskContainer.h>
#import <YFAdsSDK/YFMask.h>
#import <YFAdsSDK/YFMaterialMeta.h>
#import <YFAdsSDK/YFModels.h>
#import <YFAdsSDK/YFMotionManager.h>
#import <YFAdsSDK/YFMultiFormatter.h>
#import <YFAdsSDK/YFNativeAd.h>
#import <YFAdsSDK/YFNativeAdsManager.h>
#import <YFAdsSDK/YFNativeExpressAdapter.h>
#import <YFAdsSDK/YFNetworkSpeedMonitor.h>
#import <YFAdsSDK/YFNumberInterpolator.h>
#import <YFAdsSDK/YFOSLogger.h>
#import <YFAdsSDK/YFOrientationObserver.h>
#import <YFAdsSDK/YFPathAnimator.h>
#import <YFAdsSDK/YFPersentInteractiveTransition.h>
#import <YFAdsSDK/YFPathInterpolator.h>
#import <YFAdsSDK/YFPlatformCompat.h>
#import <YFAdsSDK/YFPlayer.h>
#import <YFAdsSDK/YFPlayerAdControlView.h>
#import <YFAdsSDK/YFPlayerConst.h>
#import <YFAdsSDK/YFPlayerControlView.h>
#import <YFAdsSDK/YFPlayerGestureControl.h>
#import <YFAdsSDK/YFPlayerController.h>
#import <YFAdsSDK/YFPlayerLogManager.h>
#import <YFAdsSDK/YFPlayerMediaControl.h>
#import <YFAdsSDK/YFPlayerMediaPlayback.h>
#import <YFAdsSDK/YFPlayerNotification.h>
#import <YFAdsSDK/YFPlayerStatusBar.h>
#import <YFAdsSDK/YFPlayerView.h>
#import <YFAdsSDK/YFPointInterpolator.h>
#import <YFAdsSDK/YFPolygonAnimator.h>
#import <YFAdsSDK/YFPolystarAnimator.h>
#import <YFAdsSDK/YFPortraitControlView.h>
#import <YFAdsSDK/YFPortraitViewController.h>
#import <YFAdsSDK/YFPresentTransition.h>
#import <YFAdsSDK/YFPrivateKit.h>
#import <YFAdsSDK/YFRadialGradientLayer.h>
#import <YFAdsSDK/YFReachabilityManager.h>
#import <YFAdsSDK/YFRenderGroup.h>
#import <YFAdsSDK/YFRenderNode.h>
#import <YFAdsSDK/YFRepeaterRenderer.h>
#import <YFAdsSDK/YFRequestModel.h>
#import <YFAdsSDK/YFResultSet.h>
#import <YFAdsSDK/YFRewardVideoAdapter.h>
#import <YFAdsSDK/YFRewardedVideoAd.h>
#import <YFAdsSDK/YFRouter.h>
#import <YFAdsSDK/YFRoundedRectAnimator.h>
#import <YFAdsSDK/YFSerialQueue.h>
#import <YFAdsSDK/YFShapeFill.h>
#import <YFAdsSDK/YFShapeCircle.h>
#import <YFAdsSDK/YFShapeGradientFill.h>
#import <YFAdsSDK/YFShapeGroup.h>
#import <YFAdsSDK/YFShapePath.h>
#import <YFAdsSDK/YFShapeRectangle.h>
#import <YFAdsSDK/YFShapeRepeater.h>
#import <YFAdsSDK/YFShapeStar.h>
#import <YFAdsSDK/YFShapeStroke.h>
#import <YFAdsSDK/YFShapeTransform.h>
#import <YFAdsSDK/YFSizeInterpolator.h>
#import <YFAdsSDK/YFShapeTrimPath.h>
#import <YFAdsSDK/YFSliderView.h>
#import <YFAdsSDK/YFSmallFloatControlView.h>
#import <YFAdsSDK/YFSplashAdapter.h>
#import <YFAdsSDK/YFSpeedLoadingView.h>
#import <YFAdsSDK/YFSplashAnimationView2.h>
#import <YFAdsSDK/YFSplashButton.h>
#import <YFAdsSDK/YFSplashEnum.h>
#import <YFAdsSDK/YFSplashEnvelopeView.h>
#import <YFAdsSDK/YFSplashView.h>
#import <YFAdsSDK/YFSplashView2.h>
#import <YFAdsSDK/YFStrokeRenderer.h>
#import <YFAdsSDK/YFTapBarAnimationView.h>
#import <YFAdsSDK/YFTouchReportView.h>
#import <YFAdsSDK/YFTransformInterpolator.h>
#import <YFAdsSDK/YFTrimPathNode.h>
#import <YFAdsSDK/YFUtilities.h>
#import <YFAdsSDK/YFValueCallback.h>
#import <YFAdsSDK/YFValueDelegate.h>
#import <YFAdsSDK/YFValueInterpolator.h>
#import <YFAdsSDK/YFVideoAd.h>
#import <YFAdsSDK/YFVolumeBrightnessView.h>
#import <YFAdsSDK/YFVideoAdViewController.h>
#import <YFAdsSDK/YF_SDImageCache.h>
#import <YFAdsSDK/YFWeakProxy.h>
#import <YFAdsSDK/YF_SDWebImageCompat.h>
#import <YFAdsSDK/YF_SDWebImageDownloaderOperation.h>
#import <YFAdsSDK/YF_SDWebImageManager.h>
#import <YFAdsSDK/YF_SDWebImageDownloader.h>
#import <YFAdsSDK/YF_SDWebImageOperation.h>
#import <YFAdsSDK/YF_SDWebImageDecoder.h>
#import <YFAdsSDK/YF_SDWebImagePrefetcher.h>
#import <YFAdsSDK/YFtie.h>
#import <YFAdsSDK/YFAdBaseViewController.h>
#import <YFAdsSDK/YFEnvelopeIntertitialAdViewController.h>
#import <YFAdsSDK/YFAdEnvelopeIntertitialAdViewController.h>


